<a href="https://colab.research.google.com/github/Sanja2000/Assignment/blob/main/movies_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
movies = pd.read_csv('/content/drive/MyDrive/MovieAssignmentData.csv')

In [ ]:
movies.head()

   color      director_name  ...  aspect_ratio  movie_facebook_likes
0  Color      James Cameron  ...          1.78                 33000
1  Color     Gore Verbinski  ...          2.35                     0
2  Color         Sam Mendes  ...          2.35                 85000
3  Color  Christopher Nolan  ...          2.35                164000
4    NaN        Doug Walker  ...           NaN                     0

[5 rows x 28 columns]

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# 1. profit
movies.budget = round(movies['budget']/1000000,2)
movies.gross = round(movies['gross']/1000000,2)

In [ ]:
movies['profit'] = movies.gross - movies.budget
movies_by_profit = movies.sort_values("profit",ascending = False)
print(movies_by_profit)

      color     director_name  ...  movie_facebook_likes  profit
0     Color     James Cameron  ...                 33000  523.51
29    Color   Colin Trevorrow  ...                150000  502.18
26    Color     James Cameron  ...                 26000  458.67
3024  Color      George Lucas  ...                 33000  449.94
3080  Color  Steven Spielberg  ...                 34000  424.45
...     ...               ...  ...                   ...     ...
5036  Color   Anthony Vallone  ...                     4     NaN
5038  Color       Scott Smith  ...                    84     NaN
5039  Color               NaN  ...                 32000     NaN
5040  Color  Benjamin Roberds  ...                    16     NaN
5041  Color       Daniel Hsia  ...                   660     NaN

[5043 rows x 29 columns]

In [ ]:
# 2. which language takes high profit

temp = movies.groupby('language')['profit'].mean().sort_values(ascending=False)
print(temp)

language
English         14.285937
Maya            10.860000
Persian          2.670000
Indonesian       1.245000
Romanian         0.600000
Zulu            -0.090000
Arabic          -0.240000
Hebrew          -0.326667
Portuguese      -0.926000
Vietnamese      -0.950000
Dzongkha        -1.290000
None            -1.400000
Dari            -1.560000
Italian         -2.588571
Russian         -2.710000
Aboriginal      -3.655000
German          -5.093846
Dutch           -7.950000
Icelandic       -9.990000
Cantonese      -10.432500
Telugu         -11.530000
Bosnian        -12.700000
Mongolian      -14.300000
Danish         -15.896667
Norwegian      -16.175000
French         -16.971892
Kazakh         -24.920000
Spanish        -24.930000
Swedish        -24.990000
Aramaic        -29.500000
Mandarin       -64.985333
Filipino       -69.830000
Czech          -83.830000
Hindi          -85.961000
Thai          -295.846667
Japanese      -557.225833
Hungarian    -2499.800000
Korean       -3287.094000
Chinese               NaN
Greek                 NaN
Kannada               NaN
Panjabi               NaN
Polish                NaN
Slovenian             NaN
Swahili               NaN
Tamil                 NaN
Urdu                  NaN
Name: profit, dtype: float64

In [ ]:
# 3.which genres makes the most money?
temp = movies.groupby('genres')['profit'].mean().sort_values(ascending=False)
print(temp)

genres
Family|Sci-Fi                                  424.450
Adventure|Animation|Drama|Family|Musical       377.780
Action|Biography|Drama|History|Thriller|War    291.320
Adventure|Drama|Fantasy|Romance                205.935
Action|Adventure|Fantasy|Sci-Fi                199.560
                                                ...
Mystery|Romance|Sci-Fi|Thriller                    NaN
Mystery|Western                                    NaN
Romance|Short                                      NaN
Thriller|War                                       NaN
Thriller|Western                                   NaN
Name: profit, Length: 914, dtype: float64

In [ ]:
# 4.Do the movies that have high vote_avergae make lot of profits ?
tempvar = movies.groupby('num_voted_users')['profit'].mean().sort_values(ascending=False)
print(tempvar)

num_voted_users
886204    523.51
418214    502.18
793059    458.67
911097    449.94
281842    424.45
           ...
342585       NaN
387508       NaN
447785       NaN
507063       NaN
610333       NaN
Name: profit, Length: 4826, dtype: float64

In [ ]:
temp = pd.DataFrame({'best directors': movies['director_name']})
count_percentage = temp.value_counts()
print(count_percentage)

best directors
Steven Spielberg    26
Woody Allen         22
Martin Scorsese     20
Clint Eastwood      20
Ridley Scott        17
                    ..
Luis Valdez          1
Lukas Moodysson      1
Luke Dye             1
Lynn Shelton         1
A. Raven Cruz        1
Length: 2398, dtype: int64

In [ ]:
# which producers generally do well?
tem = movies.groupby('director_name')['num_voted_users'].mean().sort_values(ascending=False)
print(tem)

director_name
Christopher Nolan      1013285.25
Quentin Tarantino       698832.50
Frank Darabont          684470.00
Richard Marquand        681857.00
Joss Whedon             674024.50
                          ...
Lance McDaniel               6.00
Christopher Barnard          6.00
Sam Martin                   6.00
Bill Benenson                5.00
Harry F. Millarde            5.00
Name: num_voted_users, Length: 2398, dtype: float64

In [ ]:
# finding the most popular genre
genre = movies.genres.str.split('|',expand=True).iloc[:,0:2]
genre.columns=['genre_1','genre_2']
genre.genre_2.fillna(genre.genre_1,inplace=True)
genre

          genre_1      genre_2
0          Action    Adventure
1          Action    Adventure
2          Action    Adventure
3          Action     Thriller
4     Documentary  Documentary
...           ...          ...
5038       Comedy        Drama
5039        Crime        Drama
5040        Drama       Horror
5041       Comedy        Drama
5042  Documentary  Documentary

[5043 rows x 2 columns]

In [ ]:
pd.concat([movies,genre], axis=1)
movies

      color      director_name  ...  movie_facebook_likes  profit
0     Color      James Cameron  ...                 33000  523.51
1     Color     Gore Verbinski  ...                     0    9.40
2     Color         Sam Mendes  ...                 85000  -44.93
3     Color  Christopher Nolan  ...                164000  198.13
4       NaN        Doug Walker  ...                     0     NaN
...     ...                ...  ...                   ...     ...
5038  Color        Scott Smith  ...                    84     NaN
5039  Color                NaN  ...                 32000     NaN
5040  Color   Benjamin Roberds  ...                    16     NaN
5041  Color        Daniel Hsia  ...                   660     NaN
5042  Color           Jon Gunn  ...                   456    0.09

[5043 rows x 29 columns]

In [18]:
# drop the duplicates?
movies.drop_duplicates

<bound method DataFrame.drop_duplicates of       color      director_name  ...  movie_facebook_likes  profit
0     Color      James Cameron  ...                 33000  523.51
1     Color     Gore Verbinski  ...                     0    9.40
2     Color         Sam Mendes  ...                 85000  -44.93
3     Color  Christopher Nolan  ...                164000  198.13
4       NaN        Doug Walker  ...                     0     NaN
...     ...                ...  ...                   ...     ...
5038  Color        Scott Smith  ...                    84     NaN
5039  Color                NaN  ...                 32000     NaN
5040  Color   Benjamin Roberds  ...                    16     NaN
5041  Color        Daniel Hsia  ...                   660     NaN
5042  Color           Jon Gunn  ...                   456    0.09

[5043 rows x 29 columns]>

In [19]:
# movies based on votes
movies[movies['num_voted_users'] > 25000]

                 color      director_name  ...  movie_facebook_likes  profit
0                Color      James Cameron  ...                 33000  523.51
1                Color     Gore Verbinski  ...                     0    9.40
2                Color         Sam Mendes  ...                 85000  -44.93
3                Color  Christopher Nolan  ...                164000  198.13
5                Color     Andrew Stanton  ...                 24000 -190.64
...                ...                ...  ...                   ...     ...
5008   Black and White        Kevin Smith  ...                     0    2.92
5012             Color         David Ayer  ...                 10000  -24.50
5033             Color      Shane Carruth  ...                 19000    0.41
5035             Color   Robert Rodriguez  ...                     0    2.03
5039             Color                NaN  ...                 32000     NaN

[2874 rows x 29 columns]

In [ ]:
# movies with top imdb ratings
movies[movies['num_voted_users'] > 25000].sort_values(by='imdb_score',ascending=False)

      color         director_name  ...  movie_facebook_likes  profit
1937  Color        Frank Darabont  ...                108000    3.34
3466  Color  Francis Ford Coppola  ...                 43000  128.82
3481  Color                   NaN  ...                 61000     NaN
66    Color     Christopher Nolan  ...                 37000  348.32
2837  Color  Francis Ford Coppola  ...                 14000   44.30
...     ...                   ...  ...                   ...     ...
2192  Color       Jason Friedberg  ...                     0   19.74
319   Color     Lawrence Guterman  ...                   881  -66.99
2295  Color             Bob Clark  ...                     0  -10.89
2268  Color       Jason Friedberg  ...                     0  -10.83
2834  Color            Jon M. Chu  ...                 62000   60.00

[2874 rows x 29 columns]